This is makeindex.exe, version 2.15 [MiKTeX 2.9 64-bit] (kpathsea + Thai support).
Scanning style file C:/Users/Jens/Documents/GitHub/Thesis/thesis.ist.............................done (29 attributes redefined, 0 ignored).
Scanning input file thesis.acn....done (411 entries accepted, 0 rejected).
Sorting entries......done (3830 comparisons).
Generating output file thesis.acr....done (206 lines written, 0 warnings).
Output written in thesis.acr.
Transcript written in thesis.alg.
